name: exo-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - tensorflow
  - jupyter
  - notebook
  - pip
  - pip:
    - seaborn
    - plotly
    - opencv-python 